apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
  namespace: jenkins
spec:
  type: LoadBalancer
  ports:
   - port: 80
     protocol: TCP
     targetPort: jenkins-web
  selector:
   app: jenkins