apiVersion: v1
kind: Service
metadata:
  name: gitea
  labels:
    app: gitea
  namespace: gitea
spec:
  type: LoadBalancer
  ports:
   - port: 80
     protocol: TCP
     targetPort: gitea-web
  selector:
   app: gitea