kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitea-pv-volume
  labels:
    type: local
    app: gitea
  namespace: gitea
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitea-pv-claim
  labels:
    app: gitea
  namespace: gitea
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi