apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgis
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgis
  template:
    metadata:
      labels:
        app: postgis
    spec:
      containers:
        - name: postgis
          image: postgis/postgis
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgis-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgisdb
      volumes:
        - name: postgisdb
          persistentVolumeClaim:
            claimName: postgis-pv-claim
