kind: PersistentVolume
apiVersion: v1
metadata:
  name: simplerisk-pv-volume
  labels:
    type: local
    app: simplerisk
  namespace: simplerisk
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/simplerisk"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: simplerisk-pv-claim
  labels:
    app: simplerisk
  namespace: simplerisk
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi