apiVersion: v1
kind: Service
metadata:
  name: simplerisk
  labels:
    app: simplerisk
  namespace: simplerisk
spec:
  ports:
    - port: 80
      name: "srhttp"
    - port: 443
      name: "srhttps"
  selector:
    app: simplerisk
    tier: frontend
  type: LoadBalancer