apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
  namespace: mysql
data:
  MYSQL_ROOT_PASSWORD: admin123
  PMA_HOSTS: mysql,mysql56,mysql57
  PMA_PORT: "3306"
  