apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-config
  labels:
    app: postgis
  namespace: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  PGDATA: /var/lib/postgresql/data