apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-xe-11g-pv-volume
  labels:
    type: local
  namespace: oracle-xe-11g
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/oracle-xe-11g"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-xe-11g-pv-claim
  namespace: oracle-xe-11g
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi