apiVersion: v1
kind: Service
metadata:
  name: oracle-xe-11g
  namespace: oracle-xe-11g
spec:
  ports:
  - port: 1521
    name: oracle
  - port: 8080
    name: xdb
  selector:
    app: oracle-xe-11g
  type: LoadBalancer